name: Generate OpenAPI Docs

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  html-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Redocly
        run: npm install -g @redocly/cli

      - name: Generate HTML
        run: |
          redocly build-docs etsi_004_push_mode_kms_server.yaml -o docs/kms.html
          redocly build-docs etsi_004_push_mode_qkd_server.yaml -o docs/qkd.html

      - name: Commit generated HTML
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/*.html
          git commit -m "Auto-generate HTML OpenAPI docs" || true
          git push

      - name: Compute safe branch name #github pages might break if "/" in branch name
        run: echo "SAFE_BRANCH=${GITHUB_REF_NAME//\//-}" >> $GITHUB_ENV

      - name: Deploy HTML to GitHub Pages
        # if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: ${{ env.SAFE_BRANCH }}
          exclude_assets: '**/*.pdf'

      - name: Print GitHub Pages URL
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          echo "HTML docs deployed at: https://${GITHUB_REPOSITORY_OWNER}.github.io/$REPO_NAME/${SAFE_BRANCH}/"

  pdf-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Tools
        run: |
          npm install -g @openapitools/openapi-generator-cli
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Generate Markdown (OpenAPI Generator)
        run: |
          mkdir -p docs/kms-md docs/qkd-md

          openapi-generator-cli generate \
            -i etsi_004_push_mode_kms_server.yaml \
            -g markdown \
            -o docs/kms-md

          openapi-generator-cli generate \
            -i etsi_004_push_mode_qkd_server.yaml \
            -g markdown \
            -o docs/qkd-md

          # Merge markdown into single file per spec
          cat docs/kms-md/README.md docs/kms-md/docs/*.md > docs/kms.md
          cat docs/qkd-md/README.md docs/qkd-md/docs/*.md > docs/qkd.md

      - name: Generate PDFs
        run: |
          pandoc docs/kms.md \
            -o docs/kms.pdf \
            --pdf-engine=xelatex \
            -V papersize=A4 \
            -V geometry:margin=2cm

          pandoc docs/qkd.md \
            -o docs/qkd.pdf \
            --pdf-engine=xelatex \
            -V papersize=A4 \
            -V geometry:margin=2cm
